{%- if api_ip is defined and ':' in api_ip -%}
{%- set ipv6 = True %}
{%- set network_type = 'OVNKubernetes' %}
{%- else -%}
{%- set network_type = 'OpenShiftSDN' %}
{%- set ipv6 = False %}
{%- endif -%}
{%- if virtual %}
{%- set masters = [{},{},{}] %}
{%- endif -%}
apiVersion: v1
baseDomain: {{ domain }}
networking:
  networkType: {{ network_type }}
  machineCIDR: {{ baremetal_cidr }}
  clusterNetworks:
{%- if ipv6 %}
  - cidr: fd01::/48
    hostPrefix: 64
  serviceNetwork:
  - fd02::/112
{%- else %}
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
{%- endif %}
metadata:
  name: {{ cluster }}
compute:
- name: worker
  replicas: {{ workers|length }}
controlPlane:
  name: master
  replicas: {{ masters|length }}
platform:
  baremetal:
    apiVIP: {{ api_ip }}
    dnsVIP: {{ dns_ip }}
    ingressVIP: {{ ingress_ip }}
    provisioningBridge: {{ provisioning_net }}
    provisioningNetworkInterface: {{ 'ens3' if virtual else provisioning_interface }}
    externalBridge: {{ baremetal_net }}
    libvirtURI: qemu+ssh://root@{{ config_host }}/system
    hosts:
{%- for master in masters %}
{%- set num = loop.index0|string %}
    - name: {{ cluster }}-master-{{ num }}
      role: master
      bmc:
        address: ipmi://{{ master['ipmi_address'] | default('DONTCHANGEME:623' + num)}}
        username: {{ ipmi_user }}
        password: {{ ipmi_password }}
      bootMACAddress: {{ master['provisioning_mac'] | default(provisioning_mac_prefix + ":" + "%02.d" | format(num|int + 1)| string) }}
{%- endfor %}
{%- for worker in workers %}
{%- set num = loop.index0|string %}
    - name: {{ cluster }}-worker-{{ num }}
      role: worker
      bmc:
        address: ipmi://{{ worker['ipmi_address'] | default('DONTCHANGEME:624' + num)}}
        username: {{ ipmi_user }}
        password: {{ ipmi_password }}
      bootMACAddress: {{ worker['provisioning_mac'] | default(provisioning_mac_prefix + ":" + "%02.d" | format(num|int + 11)| string) }}
      hardwareProfile: unknown
{%- endfor %}
{%- if ca is defined %}
additionalTrustBundle: |
 {{ ca | replace('\n', '\n ') }}
{%- endif %}
{%- if disconnected_url is defined -%}
imageContentSources:
- mirrors:
  - {{ disconnected_url }}/ocp/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - {{ disconnected_url }}/ocp/release
  source: registry.svc.ci.openshift.org/ocp/release
{%- endif %}
