apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /pv001
    server: ${PRIMARY_IP}
  persistentVolumeReclaimPolicy: Recycle
