apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  cpu:
    isolated: "0-8"
    nonIsolated: "9-15"
    reserved: "9-15"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
  realTimeKernel:
    enabled: true
