parameters:
 version: latest
 driver: kvm2
 memory: 8192

minikube:
 image: Fedora-Cloud-Base-28-1.1.x86_64.qcow2
 numcpus: 2
 cpumodel: host-model
 cpuflags:
  - name: arat
    enable: false
  - name: clflushopt
    enable: false
 memory: {{ memory }}
 reservedns: true
 nets:
  - default
 disks:
  - size: 40
 pool: default
 files:
  - path: /root/network.yml
    origin: network.yml
  - path: /root/minikube.sh
    origin: minikube.sh
